{
 "title": "New dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "(в процентах, 100 - idle)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", job=\"nodeexporter\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество свободной оперативной памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\", job=\"nodeexporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}